# Generated by Django 5.0.6 on 2024-06-30 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lernspiel_server', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sourcefile',
            new_name='lernspiel_s_content_f8146f_idx',
            old_name='lernspiel_s_content_604ecf_idx',
        ),
    ]
