# Generated by Django 5.0.6 on 2024-06-26 23:26

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('lernspiel_server', '0002_usergroup'), ('lernspiel_server', '0003_alter_usergroup_options')]

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('lernspiel_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
            ],
            options={
                'verbose_name': 'User Group',
                'verbose_name_plural': 'User Groups',
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
