# Generated by Django 5.0.6 on 2024-07-01 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lernspiel_server', '0002_rename_lernspiel_s_content_604ecf_idx_lernspiel_s_content_f8146f_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mediafile',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='mediafile',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='mediafile',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='sourcefile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sourcefile',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sourcefile',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='sourcefile',
            name='modified_by',
        ),
    ]
