# Generated by Django 5.0.6 on 2024-06-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('lernspiel_server', '0004_site'), ('lernspiel_server', '0005_site_header_bg_site_link_color_site_logo_width'), ('lernspiel_server', '0006_alter_site_logo_width'), ('lernspiel_server', '0007_alter_site_logo_width')]

    dependencies = [
        ('lernspiel_server', '0003_alter_usergroup_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('domain', models.CharField(max_length=100, verbose_name='Domain Name')),
                ('name', models.CharField(max_length=255, verbose_name='Display Name')),
                ('header_bg', models.CharField(default='#234769', max_length=100, verbose_name='Header Background')),
                ('link_color', models.CharField(default='crimson', max_length=20, verbose_name='Link Color')),
                ('logo_width', models.CharField(default='20em', max_length=20, verbose_name='Logo Width')),
            ],
            options={
                'verbose_name': 'Website',
                'verbose_name_plural': 'Websites',
            },
        ),
    ]
