# Generated by Django 5.0.6 on 2024-06-26 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lernspiel_server', '0002_usergroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergroup',
            options={'verbose_name': 'User Group', 'verbose_name_plural': 'User Groups'},
        ),
    ]
