# Generated by Django 5.0.6 on 2024-06-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lernspiel_server', '0003_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='object_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='site',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
