# Generated by Django 5.0.6 on 2024-06-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lernspiel_server', '0003_alter_usergroup_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('domain', models.CharField(max_length=100, verbose_name='Domain Name')),
                ('name', models.CharField(max_length=255, verbose_name='Display Name')),
            ],
            options={
                'verbose_name': 'Website',
                'verbose_name_plural': 'Websites',
            },
        ),
    ]
