# Generated by Django 5.0.6 on 2024-06-27 19:07

import django.db.models.deletion
import lernspiel_server.db
import ls_games_core.models.game_variants
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('game_type', models.CharField(max_length=64, verbose_name='Game Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('par_object_id', models.UUIDField(null=True)),
                ('par_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Game Variant',
                'verbose_name_plural': 'Game Variants',
                'ordering': ['name'],
            },
            bases=(models.Model, lernspiel_server.db.CreatedModifiedByMixin),
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('file_type', models.SmallIntegerField(choices=[(1, 'HTML Template'), (2, 'CSS Stylesheet'), (3, 'JS Source File')], verbose_name='File Type')),
                ('sort_order', models.SmallIntegerField(verbose_name='Sort Order')),
                ('source_file', models.FileField(upload_to=ls_games_core.models.game_variants.SourceFile._calc_file_path, verbose_name='Source File')),
                ('game_variant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='ls_games_core.gamevariant')),
            ],
            options={
                'verbose_name': 'Source File',
                'verbose_name_plural': 'Source Files',
                'ordering': ['file_type', 'sort_order'],
            },
            bases=(models.Model, lernspiel_server.db.CreatedModifiedByMixin),
        ),
        migrations.AddIndex(
            model_name='gamevariant',
            index=models.Index(fields=['par_content_type', 'par_object_id'], name='ls_games_co_par_con_2a5eb2_idx'),
        ),
    ]
