# Generated by Django 5.0.6 on 2024-06-27 03:13

import django.db.models.deletion
import lernspiel_server.db
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('file_type', models.SmallIntegerField(choices=[(1, 'HTML Template'), (2, 'CSS Stylesheet'), (3, 'JS Source File')], verbose_name='File Type')),
                ('sort_order', models.SmallIntegerField(verbose_name='Sort Order')),
            ],
            options={
                'verbose_name': 'Source File',
                'verbose_name_plural': 'Source Files',
                'ordering': ['file_type', 'sort_order'],
            },
            bases=(models.Model, lernspiel_server.db.CreatedModifiedByMixin),
        ),
        migrations.CreateModel(
            name='GameVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('game_type', models.CharField(max_length=64, verbose_name='Game Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('par_object_id', models.PositiveIntegerField()),
                ('par_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Game Variant',
                'verbose_name_plural': 'Game Variants',
                'ordering': ['name'],
            },
            bases=(models.Model, lernspiel_server.db.CreatedModifiedByMixin),
        ),
    ]
