# Generated by Django 5.0.6 on 2024-06-27 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls_games_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcefile',
            name='game_variant',
            field=models.ForeignKey(default=0, editable=False, on_delete=django.db.models.deletion.CASCADE, to='ls_games_core.gamevariant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamevariant',
            name='par_object_id',
            field=models.UUIDField(),
        ),
    ]
