# Generated by Django 5.0.6 on 2024-06-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls_game_meta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventparametermeta',
            options={'verbose_name': 'Event Parameter', 'verbose_name_plural': 'Event Parameters'},
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='ls_game_met_parent__7b8248_idx',
            old_name='ls_game_met_parent__252ed2_idx',
        ),
        migrations.AlterField(
            model_name='category',
            name='position',
            field=models.SmallIntegerField(verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='eventparametermeta',
            name='data_type',
            field=models.CharField(choices=[('plain', 'Plain Text'), ('text', 'Formatted Text'), ('num', 'Number'), ('bool', 'Boolean'), ('dict', 'Dictionary')], max_length=10, verbose_name='Data Type'),
        ),
        migrations.AlterField(
            model_name='propertymeta',
            name='data_type',
            field=models.CharField(choices=[('plain', 'Plain Text'), ('text', 'Formatted Text'), ('num', 'Number'), ('bool', 'Boolean'), ('dict', 'Dictionary')], max_length=10, verbose_name='Data Type'),
        ),
    ]
