# Generated by Django 5.0.6 on 2024-07-19 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls_ui_static_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='blur',
            field=models.PositiveSmallIntegerField(default=0, help_text='Between 0 and 100, 0 = no blur', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Blur %'),
        ),
        migrations.AddField(
            model_name='background',
            name='overlay_alpha',
            field=models.PositiveSmallIntegerField(default=0, help_text='Between 0 and 100, 0 = fully transparent', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Overlay Opacity %'),
        ),
        migrations.AddField(
            model_name='background',
            name='overlay_color',
            field=models.CharField(blank=True, default='', help_text='Hexadecimal CSS color code', max_length=7, verbose_name='Overlay Color'),
        ),
    ]
