# Generated by Django 5.0.6 on 2024-07-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lernspiel_server', '0003_remove_mediafile_created_at_and_more'),
        ('ls_ui_static_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet_t',
            options={'ordering': ['parent', 'language'], 'verbose_name': 'Translation', 'verbose_name_plural': 'Translations'},
        ),
        migrations.AddIndex(
            model_name='snippet_t',
            index=models.Index(fields=['parent', 'language'], name='ls_ui_stati_parent__4213d5_idx'),
        ),
    ]
