# Generated by Django 5.0.6 on 2024-07-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls_ui_static_pages', '0002_alter_snippet_t_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textpage',
            name='login_required',
            field=models.BooleanField(default=False, verbose_name='Login Required'),
        ),
        migrations.AlterField(
            model_name='textpage',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Publish Page'),
        ),
    ]
