# Generated by Django 5.0.6 on 2024-07-16 01:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lernspiel_server', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('edit_key', models.CharField(blank=True, editable=False, max_length=64, verbose_name='Edit Key')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('created_by', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Game Definition',
                'verbose_name_plural': 'Game Definitions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GameDefinition_T',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lernspiel_server.language')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='ls_game_definition.gamedefinition')),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
                'ordering': ['parent', 'language'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParticipantRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('limit', models.SmallIntegerField(blank=True, default=0, verbose_name='Max. Allowed Participants')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_roles', to='ls_game_definition.gamedefinition')),
            ],
            options={
                'verbose_name': 'Participant Role',
                'verbose_name_plural': 'Participant Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantRole_T',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lernspiel_server.language')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='ls_game_definition.participantrole')),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
                'ordering': ['parent', 'language'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='gamedefinition',
            index=models.Index(fields=['name'], name='ls_game_def_name_462f56_idx'),
        ),
        migrations.AddIndex(
            model_name='gamedefinition_t',
            index=models.Index(fields=['parent', 'language'], name='ls_game_def_parent__7aedcb_idx'),
        ),
        migrations.AddIndex(
            model_name='participantrole',
            index=models.Index(fields=['name'], name='ls_game_def_name_0077eb_idx'),
        ),
        migrations.AddIndex(
            model_name='participantrole_t',
            index=models.Index(fields=['parent', 'language'], name='ls_game_def_parent__34e9cd_idx'),
        ),
    ]
